// Simple dark theme. Unused keys are retained as example material
"theme"
{
	"qt"
	{
		"Style"					"Fusion"
		"WindowsTitleBarColor"	"0 0 0"
		"WindowText"  			"255 255 255"
		"Button"  				"53 53 53"
		"Text"  				"255 255 255"
		"BrightText"  			"200 0 0"
		"ButtonText"  			"255 255 255"
		"Base"  				"25 25 25"
		"Window"  				"40 40 40"
		"Highlight"  			"219 65 65"
		"HighlightedText" 		"10 10 10"
		"AlternateBase" 		"40 40 40"
		"ToolTipBase"  			"25 25 25"
		"ToolTipText" 			"255 255 255"
		//"PlaceholderText" 	""	
		//"Light"  				""
		//"Midlight"  			""
		//"Dark"  				""
		//"Mid" 				""
		//"Link"  				""
		//"LinkVisited" 		""
		//"Shadow" 				""

		"disabled"
		{
			"Text"  				"102 102 102"
			"BrightText"  			"128 0 0"
			"Button"  				"20 20 20"
			"ButtonText"  			"96 96 96"

			"Highlight"  			"219 65 65"
			"HighlightedText" 		"10 10 10"
		}
		"inactive"
		{
			"Button"			"38 38 38"
			"Text"  			"204 204 204"
			"BrightText"  		"192 0 0"
			"ButtonText"		"204 204 204"
			"Base" 				"15 15 15"
			"Window"  			"25 25 25"
			"Highlight" 		"128 38 38"
			"HighlightedText" 	"5 5 5"
			"AlternateBase" 	"25 25 25"
		}
	}
}

