name: FGD Build and Folder Copy
on:
  pull_request:
    branches:
      - master

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install srctools
        run: python -m pip install git+https://github.com/StrataSource/srctools.git

      - name: FGD build and folder copy
        run: .\build.bat fgd all

      - name: Artifact upload
        uses: actions/upload-artifact@v4
        with:
          name: build_${{ runner.os }}-${{ github.sha }}
          path: ./build/*
          if-no-files-found: error

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install srctools
        run: python3 -m pip install git+https://github.com/StrataSource/srctools.git

      - name: FGD build and folder copy
        run: bash ./build.sh fgd all
